---
title: "About"
output: 
  html_document:
    includes:
       in_header: GA_Script.html
       after_body: footer.html
---

Welcome to the website for the **C**oastlines and people **O**pen data and **M**achin**E** learning sprin**T**. COMET is a series of 72hr events focused on data-driven [Coastlines and People (CoPe)](https://coastlinesandpeople.org) science. 

We have funding (lodging, travel, per diem) for ~10-15 participants at each of the 3 events (two in Kitty Hawk, NC and one in Boulder, CO). Each participant will need to bring a research idea to pitch to the others - ideas should focus on using open data to do science (very open ended, we'll get to that later). After project pitches, participants will divide up into self-selected groups to work on ideas for 72 hrs (some ideas will unfortunately be left behind). 

Each event is likely to be heavy on computation, and our intention is for all code written at the event to be open source, put on github, and given a DOI (by the end of the event). A final 'report out' will allow each group to present what they accomplished at the end of the 72 hours, and groups will also submit a report/working paper [EarthArXiv](https://eartharxiv.org). Our intention is for these open deliverables to be the seeds of future research between participants and the wider CoPe Community.

We will soon be soliciting applications for each 72 hr event. Check out the [Apply! page](https://copecomet.github.io/Apply.html) for the short application procedure. 

Still have questions? Check out the site, specifically the [FAQ](https://copecomet.github.io/FAQ.html), or send us a [message](https://copecomet.github.io/Contact.html).


